// Copyright 2021 Joric (@joric)
// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H

enum layers {
    _QWERTY = 0,
    _LOWER,
    _RAISE,
    _ADJUST,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_QWERTY] = LAYOUT(KC_LGUI, KC_RBRC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RGUI, KC_GRV, LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RGUI_T(KC_SCLN), KC_QUOT, KC_CAPS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLS, LT(3,KC_TAB), LT(2,KC_SPC), LT(1,KC_ENT), LT(1,KC_ESC), LT(2,KC_BSPC), LT(3,KC_DEL)),
    [_LOWER] = LAYOUT(KC_PLUS, LGUI_T(KC_NUM), KC_PSLS, KC_AMPR, KC_ASTR, KC_LPRN, KC_DQUO, KC_EQL, KC_QUOT, KC_GRV, KC_BSLS, KC_PIPE, RGUI_T(KC_PEQL), KC_UNDS, LCTL_T(KC_PCMM), KC_PAST, KC_DLR, KC_PERC, KC_CIRC, KC_QUOT, KC_MINS, KC_LPRN, KC_LBRC, KC_LCBR, KC_LT, RCTL_T(KC_PMNS), LALT_T(KC_PDOT), KC_RPRN, KC_EXLM, KC_AT, KC_HASH, KC_GRV, KC_UNDS, KC_RPRN, KC_RBRC, KC_RCBR, KC_GT, RALT_T(KC_PEQL), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_RAISE] = LAYOUT(LGUI_T(KC_NUM), KC_ENT, KC_SLSH, KC_7, KC_8, KC_9, KC_PLUS, CW_TOGG, KC_PGUP, KC_UP, KC_PGDN, KC_SCRL, KC_VOLU, RGUI_T(KC_SCRL), KC_COMM, LGUI_T(KC_PAST), LALT_T(KC_4), LCTL_T(KC_5), LSFT_T(KC_6), KC_MINS, KC_HOME, RSFT_T(KC_LEFT), RCTL_T(KC_DOWN), RALT_T(KC_RGHT), RGUI_T(KC_END), KC_PAUS, KC_DOT, KC_0, KC_1, KC_2, KC_3, KC_EQL, KC_CAPS, KC_INS, KC_APP, KC_DEL, KC_PSCR, KC_VOLD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_ADJUST] = LAYOUT(QK_BOOT, LGUI_T(KC_NO), KC_SCRL, KC_F7, KC_F8, KC_F9, KC_F10, QK_AREP, KC_BRIU, KC_VOLU, KC_BRID, KC_SCRL, KC_EXEC, QK_BOOT, LCTL_T(KC_NO), LGUI_T(KC_PSCR), LALT_T(KC_F4), LCTL_T(KC_F5), LSFT_T(KC_F6), KC_F11, KC_APP, RSFT_T(KC_MPRV), RCTL_T(KC_VOLD), RALT_T(KC_MNXT), RGUI_T(KC_PSCR), RCTL_T(KC_NO), LALT_T(KC_NO), KC_PAUS, KC_F1, KC_F2, KC_F3, KC_F12, QK_REP, KC_MSTP, KC_MUTE, KC_MPLY, KC_PAUS, KC_HELP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};