// Copyright 2021 Joric (@joric)
// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H

enum layers {
  _QWERTY = 0,
  _DVORAK = 1,
  _COLEMAK = 2,
  _LOWER = 3,
  _RAISE = 4,
  _ADJUST = 5,
  _SYMBOLS = 6,
  _MULTIMEDIA = 7,
  _MOUSE = 8,
};

enum combos {
  // QWERTY
  SD_CAPS,
  DF_QUOT,
  ER_LBRC,
  WE_GRV,
  CV_BSLS,

  JK_QUOT,
  KL_CAPS,
  UI_RBRC,
  IO_GRV,
  MCMM_BSLS,
  GH_MOUSE_LAYER,

  // DVORAK
  OE_CAPS,
  EU_QUOT,
  DOTP_LBRC,
  CMMDOT_GRV,
  JK_BSLS,

  HT_QUOT,
  TN_CAPS,
  GC_RBRC,
  CR_GRV,
  MW_BSLS,
  ID_MOUSE_LAYER,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(KC_NO, KC_NO, LT(_MULTIMEDIA,KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, LT(_MULTIMEDIA,KC_P), KC_NO, KC_NO, KC_NO, LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), LT(_SYMBOLS,KC_G), LT(_SYMBOLS,KC_H), RSFT_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RGUI_T(KC_SCLN), KC_NO, KC_NO, LT(_MOUSE,KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, LT(_MOUSE,KC_SLSH), KC_NO, LT(_ADJUST,KC_TAB), LT(_RAISE,KC_SPC), LT(_LOWER,KC_ENT), LT(_LOWER,KC_ESC), LT(_RAISE,KC_BSPC), LT(_ADJUST,KC_DEL)),
  [1] = LAYOUT(KC_NO, KC_NO, LT(_MULTIMEDIA,KC_QUOT), KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, LT(_MULTIMEDIA,KC_L), KC_NO, KC_NO, KC_NO, LGUI_T(KC_A), LALT_T(KC_O), LCTL_T(KC_E), LSFT_T(KC_U), LT(_SYMBOLS,KC_I), LT(_SYMBOLS,KC_D), RSFT_T(KC_H), RCTL_T(KC_T), RALT_T(KC_N), RGUI_T(KC_S), KC_NO, KC_NO, LT(_MOUSE,KC_SCLN), KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, LT(_MOUSE,KC_Z), KC_NO, LT(_ADJUST,KC_TAB), LT(_RAISE,KC_SPC), LT(_LOWER,KC_ENT), LT(_LOWER,KC_ESC), LT(_RAISE,KC_BSPC), LT(_ADJUST,KC_DEL)),
  [2] = LAYOUT(KC_NO, KC_NO, LT(_MULTIMEDIA,KC_Q), KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, LT(_MULTIMEDIA,KC_SCLN), KC_NO, KC_NO, KC_NO, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), LT(_SYMBOLS,KC_G), LT(_SYMBOLS,KC_M), RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O), KC_NO, KC_NO, LT(_MOUSE,KC_Z), KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, LT(_MOUSE,KC_SLSH), KC_NO, LT(_ADJUST,KC_TAB), LT(_RAISE,KC_SPC), LT(_LOWER,KC_ENT), LT(_LOWER,KC_ESC), LT(_RAISE,KC_BSPC), LT(_ADJUST,KC_DEL)),
  [3] = LAYOUT(KC_NO, KC_NO, KC_PSLS, KC_AMPR, KC_ASTR, KC_LPRN, KC_PPLS, KC_PENT, KC_P7, KC_P8, KC_P9, KC_PCMM, KC_NO, KC_NO, KC_NO, KC_PAST, KC_DLR, KC_PERC, KC_CIRC, KC_PMNS, KC_NUM, RSFT_T(KC_P4), RCTL_T(KC_P5), RALT_T(KC_P6), RGUI_T(KC_PEQL), KC_NO, KC_NO, KC_RPRN, KC_EXLM, KC_AT, KC_HASH, KC_PCMM, KC_P0, KC_P1, KC_P2, KC_P3, KC_PDOT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [4] = LAYOUT(KC_NO, KC_NO, KC_SLSH, KC_7, KC_8, KC_9, KC_PLUS, KC_ENT, KC_INS, KC_HOME, KC_PGUP, KC_NUM, KC_NO, KC_NO, KC_NO, LGUI_T(KC_PAST), LALT_T(KC_4), LCTL_T(KC_5), LSFT_T(KC_6), KC_MINS, KC_APP, RSFT_T(KC_LEFT), RCTL_T(KC_DOWN), RALT_T(KC_UP), RGUI_T(KC_RGHT), KC_NO, KC_NO, KC_0, KC_1, KC_2, KC_3, KC_EQL, KC_ESC, KC_DEL, KC_END, KC_PGDN, KC_PSCR, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [5] = LAYOUT(KC_NO, KC_NO, KC_PAUS, KC_F7, KC_F8, KC_F9, KC_F10, KC_ENT, KC_INS, KC_HOME, KC_PGUP, KC_PAUS, KC_NO, KC_NO, KC_NO, LGUI_T(KC_SCRL), LALT_T(KC_F4), LCTL_T(KC_F5), LSFT_T(KC_F6), KC_F11, KC_APP, RSFT_T(KC_MPRV), RCTL_T(KC_VOLD), RALT_T(KC_VOLU), RGUI_T(KC_MNXT), KC_NO, KC_NO, KC_PSCR, KC_F1, KC_F2, KC_F3, KC_F12, KC_ESC, KC_DEL, KC_END, KC_PGDN, KC_PSCR, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [6] = LAYOUT(KC_NO, KC_NO, KC_SLSH, KC_AMPR, KC_PAST, KC_TILD, KC_DQUO, KC_PIPE, KC_COLN, KC_ASTR, KC_SCLN, KC_QUES, KC_NO, KC_NO, KC_NO, KC_SCLN, KC_COLN, KC_EQL, KC_MINS, KC_QUOT, KC_BSLS, KC_LPRN, KC_LBRC, KC_LCBR, KC_LT, KC_NO, KC_NO, KC_LT, KC_GT, KC_PPLS, KC_UNDS, KC_GRV, KC_SLSH, KC_RPRN, KC_RBRC, KC_RCBR, KC_GT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [7] = LAYOUT(KC_NO, KC_NO, KC_SCRL, KC_BRIU, KC_BRID, KC_HELP, DF(2), DF(2), KC_HELP, KC_BRID, KC_BRIU, KC_SCRL, KC_NO, KC_NO, KC_NO, KC_MNXT, KC_VOLU, KC_VOLD, KC_MPRV, DF(1), DF(1), KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, KC_NO, KC_EXEC, KC_MPLY, KC_MUTE, KC_MSTP, DF(0), DF(0), KC_MSTP, KC_MUTE, KC_MPLY, KC_EXEC, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [8] = LAYOUT(KC_NO, KC_NO, KC_BTN5, KC_BTN2, KC_BTN3, KC_BTN1, KC_BTN4, KC_BTN4, KC_BTN1, KC_BTN3, KC_BTN2, KC_BTN5, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_MS_R, KC_MS_U, KC_MS_D, KC_MS_L, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_ACL0, KC_NO, KC_NO, DF(0), KC_WH_R, KC_WH_U, KC_WH_D, KC_WH_L, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, DF(0), KC_NO, KC_ACL0, QK_LOCK, KC_ACL2, KC_ACL2, QK_LOCK, KC_ACL0)
};

// QWERTY
const uint16_t PROGMEM q_sd_combo[] = {LALT_T(KC_S), LCTL_T(KC_D), COMBO_END};
const uint16_t PROGMEM q_df_combo[] = {LCTL_T(KC_D), LSFT_T(KC_F), COMBO_END};
const uint16_t PROGMEM q_er_combo[] = {KC_E, KC_R, COMBO_END};
const uint16_t PROGMEM q_we_combo[] = {KC_W, KC_E, COMBO_END};
const uint16_t PROGMEM q_cv_combo[] = {KC_C, KC_V, COMBO_END};

const uint16_t PROGMEM q_jk_combo[] = {RSFT_T(KC_J), RCTL_T(KC_K), COMBO_END};
const uint16_t PROGMEM q_kl_combo[] = {RCTL_T(KC_K), RALT_T(KC_L), COMBO_END};
const uint16_t PROGMEM q_ui_combo[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM q_io_combo[] = {KC_I, KC_O, COMBO_END};
const uint16_t PROGMEM q_mcmm_combo[] = {KC_M, KC_COMM, COMBO_END};
const uint16_t PROGMEM q_gh_combo[] = {LT(_SYMBOLS,KC_G), LT(_SYMBOLS,KC_H), COMBO_END};

// DVORAK
const uint16_t PROGMEM d_oe_combo[] = {LALT_T(KC_O), LCTL_T(KC_E), COMBO_END};
const uint16_t PROGMEM d_eu_combo[] = {LCTL_T(KC_E), LSFT_T(KC_U), COMBO_END};
const uint16_t PROGMEM d_dotp_combo[] = {KC_DOT, KC_P, COMBO_END};
const uint16_t PROGMEM d_cmmdot_combo[] = {KC_COMM, KC_DOT, COMBO_END};
const uint16_t PROGMEM d_jk_combo[] = {KC_J, KC_K, COMBO_END};

const uint16_t PROGMEM d_ht_combo[] = {RSFT_T(KC_H), RCTL_T(KC_T), COMBO_END};
const uint16_t PROGMEM d_tn_combo[] = {RCTL_T(KC_T), RALT_T(KC_N), COMBO_END};
const uint16_t PROGMEM d_gc_combo[] = {KC_G, KC_C, COMBO_END};
const uint16_t PROGMEM d_cr_combo[] = {KC_C, KC_R, COMBO_END};
const uint16_t PROGMEM d_mw_combo[] = {KC_M, KC_W, COMBO_END};
const uint16_t PROGMEM d_id_combo[] = {LT(_SYMBOLS,KC_I), LT(_SYMBOLS,KC_D), COMBO_END};


combo_t key_combos[COMBO_COUNT] = {
  // QWERTY
  [SD_CAPS] = COMBO(q_sd_combo, KC_CAPS),
  [DF_QUOT] = COMBO(q_df_combo, KC_QUOT),
  [ER_LBRC] = COMBO(q_er_combo, KC_LBRC),
  [WE_GRV] = COMBO(q_we_combo, KC_GRV),
  [CV_BSLS] = COMBO(q_cv_combo, KC_BSLS),

  [JK_QUOT] = COMBO(q_jk_combo, KC_QUOT),
  [KL_CAPS] = COMBO(q_kl_combo, KC_CAPS),
  [UI_RBRC] = COMBO(q_ui_combo, KC_RBRC),
  [IO_GRV] = COMBO(q_io_combo, KC_GRV),
  [MCMM_BSLS] = COMBO(q_mcmm_combo, KC_BSLS),
  [GH_MOUSE_LAYER] = COMBO(q_gh_combo, DF(_MOUSE)),

  // DVORAK
  [OE_CAPS] = COMBO(d_oe_combo, KC_CAPS),
  [EU_QUOT] = COMBO(d_eu_combo, KC_QUOT),
  [DOTP_LBRC] = COMBO(d_dotp_combo, KC_LBRC),
  [CMMDOT_GRV] = COMBO(d_cmmdot_combo, KC_GRV),
  [JK_BSLS] = COMBO(d_jk_combo, KC_BSLS),

  [HT_QUOT] = COMBO(d_ht_combo, KC_QUOT),
  [TN_CAPS] = COMBO(d_tn_combo, KC_CAPS),
  [GC_RBRC] = COMBO(d_gc_combo, KC_RBRC),
  [CR_GRV] = COMBO(d_cr_combo, KC_GRV),
  [MW_BSLS] = COMBO(d_mw_combo, KC_BSLS),
  [ID_MOUSE_LAYER] = COMBO(d_id_combo, DF(_MOUSE)),
};
